### ISSUE TITLE
Doesn't seem to be reading dbName in

### ISSUE THREAD

**Issue by joshchang** [casbin/casdoor#2487]
Hi, I have the following docker-compose:

```
services:
  postgres-casdoor:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_DB: casdoor
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: admin
    ports:
      - 5433:5433
    restart: always
    networks:
      - postgres-network
    expose:
      - "5433"
    command: -p 5433
  casdoor:
    restart: always
    image: docker.io/casbin/casdoor:latest
    entrypoint: /bin/sh -c './server --createDatabase=true'
    ports:
      - "8000:8082"
      - "7000:7000"
    depends_on:
      - postgres-casdoor
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./backend_golang/config:/conf/
    networks:
      - postgres-network
```
and corresponding app.conf

```
POSTGRES_PASSWORD=pass
POSTGRES_USER=admin
POSTGRES_DB=casdoor
appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = postgres
dataSourceName = "user=admin password=pass host=localhost port=5433 sslmode=disable sslmode=disable dbname=casdoor"
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableGzip = true
ldapServerPort = 389
radiusServerPort = 1812
radiusSecret = "secret"
quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
initDataFile = "./init_data.json"
frontendBaseDir = "../casdoor"
```
I'm running into the error message on start (when creating the DB tables)

```
glance-casdoor-1           | goroutine 1 [running]:
glance-casdoor-1           | github.com/casdoor/casdoor/object.InitAdapter()
glance-casdoor-1           |    /go/src/casdoor/object/ormer.go:84 +0x24b
glance-casdoor-1           | main.main()
glance-casdoor-1           |    /go/src/casdoor/main.go:35 +0x46
glance-casdoor-1           | panic: pq: database "admin" does not exist
```

Any idea what is going on? It doesn't seem to be reading the dbName field in the config file
